"use client";

import * as React from "react";
import { Badge } from "@/components/ui/badge";
import { SectionHeader } from "@/components/ui/section-header";
import { ArrowRight, Brain, Code, Rocket, Zap } from "lucide-react";

const workflowSteps = [
  {
    icon: Brain,
    title: "AI Strategy",
    description: "Analyze requirements and choose the right AI tools for maximum impact",
    details: ["Claude for complex reasoning", "GitHub Copilot for code completion", "ChatGPT for brainstorming"],
    color: "text-purple-500",
    bg: "bg-purple-500/10",
  },
  {
    icon: Code,
    title: "AI-Assisted Development",
    description: "Write code 10x faster with AI pair programming and automated testing",
    details: ["AI-generated boilerplate", "Automated test suites", "Code review & optimization"],
    color: "text-blue-500",
    bg: "bg-blue-500/10",
  },
  {
    icon: Zap,
    title: "Rapid Iteration",
    description: "Deploy early, get feedback, and iterate with AI-powered improvements",
    details: ["CI/CD automation", "Performance monitoring", "User feedback integration"],
    color: "text-yellow-500",
    bg: "bg-yellow-500/10",
  },
  {
    icon: Rocket,
    title: "Scale & Optimize",
    description: "Use AI insights to scale features and optimize for growth",
    details: ["Performance analytics", "Feature flag management", "Automated scaling"],
    color: "text-green-500",
    bg: "bg-green-500/10",
  },
];

export function AIWorkflow() {
  return (
    <section className="py-20 bg-surface/50">
      <div className="container px-4">
        <div className="mx-auto max-w-6xl space-y-16">
          {/* Header */}
          <div className="text-center">
            <SectionHeader
              title="My AI-First Development Process"
              subtitle="How I ship software 10x faster by orchestrating AI systems at every stage"
            />
            <div className="mt-6">
              <Badge variant="outline" className="text-accent-primary border-accent-primary/20">
                90% of code generated by AI • 10x faster delivery
              </Badge>
            </div>
          </div>

          {/* Workflow Steps */}
          <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-4">
            {workflowSteps.map((step, index) => (
              <div key={step.title} className="relative">
                <div className="glass-card p-6 h-full hover-lift group">
                  {/* Step Number & Icon */}
                  <div className="flex items-center gap-3 mb-4">
                    <div className={`${step.bg} p-2 rounded-lg`}>
                      <step.icon className={`h-5 w-5 ${step.color}`} />
                    </div>
                    <Badge variant="outline" className="text-xs">
                      Step {index + 1}
                    </Badge>
                  </div>

                  {/* Content */}
                  <div className="space-y-3">
                    <h3 className="font-semibold text-foreground group-hover:text-accent-primary transition-colors">
                      {step.title}
                    </h3>
                    <p className="text-text-weak text-sm leading-relaxed">
                      {step.description}
                    </p>
                    
                    {/* Details */}
                    <ul className="space-y-1">
                      {step.details.map((detail) => (
                        <li key={detail} className="text-xs text-text-muted flex items-center gap-2">
                          <div className="w-1 h-1 rounded-full bg-accent-primary" />
                          {detail}
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>

                {/* Arrow connector (hidden on last item) */}
                {index < workflowSteps.length - 1 && (
                  <div className="hidden lg:block absolute top-1/2 -right-4 transform -translate-y-1/2 z-10">
                    <ArrowRight className="h-6 w-6 text-accent-primary" />
                  </div>
                )}
              </div>
            ))}
          </div>

          {/* Stats Section */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 pt-8 border-t border-border/30">
            <div className="text-center">
              <div className="text-3xl font-bold text-accent-primary mb-2">
                <span className="gradient-text">4-6 weeks</span>
              </div>
              <p className="text-sm text-text-muted">Traditional development time</p>
            </div>
            <div className="text-center">
              <div className="text-3xl font-bold text-accent-primary mb-2">
                <span className="gradient-text">3-5 days</span>
              </div>
              <p className="text-sm text-text-muted">AI-accelerated delivery</p>
            </div>
            <div className="text-center">
              <div className="text-3xl font-bold text-accent-primary mb-2">
                <span className="gradient-text">10x</span>
              </div>
              <p className="text-sm text-text-muted">Speed improvement</p>
            </div>
          </div>

          {/* Tools Section */}
          <div className="glass-card p-8 rounded-lg">
            <h3 className="font-semibold text-foreground mb-4 text-center">My AI Development Stack</h3>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              {[
                "Claude Sonnet 3.5",
                "GitHub Copilot",
                "Cursor IDE",
                "Vercel AI SDK",
                "OpenAI GPT-4",
                "Anthropic API",
                "Perplexity Pro",
                "ChatGPT Plus"
              ].map((tool) => (
                <div key={tool} className="text-center p-3 hover-lift">
                  <Badge variant="outline" className="text-xs w-full">
                    {tool}
                  </Badge>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}