"use client";

import * as React from "react";
import { ArrowRight, ExternalLink } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";

export function Hero() {
  const scrollToWork = () => {
    const workSection = document.getElementById("work");
    if (workSection) {
      workSection.scrollIntoView({ behavior: "smooth" });
    }
  };

  return (
    <section className="relative py-20 min-h-screen flex items-center justify-center bg-background">
      {/* Content */}
      <div className="container px-4 py-32">
        <div className="mx-auto max-w-6xl space-y-12 text-center">
          <div>
            <Badge
              variant="outline"
              className="text-accent-primary border-accent-primary/20 mb-6 pulse-glow"
            >
              Made with Claude
            </Badge>
          </div>

          <h1 className="text-foreground text-4xl font-bold tracking-tight md:text-6xl lg:text-7xl">
            Ship{" "}
            <span className="gradient-text">10x faster</span> with AI orchestration.
          </h1>

          <p className="text-text-weak mx-auto max-w-3xl text-lg leading-relaxed md:text-xl">
            I design, architect, and ship ambitious software by orchestrating AI
            systems end‑to‑end.{" "}
            <span className="text-foreground font-medium">
              From concept to production in days, not months.
            </span>
          </p>

          {/* Metrics Section */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 pt-8 max-w-4xl mx-auto">
            <div className="glass-card p-6 rounded-lg hover-lift">
              <div className="text-3xl font-bold text-accent-primary mb-2">15+</div>
              <div className="text-sm text-text-muted">AI-Built Projects</div>
            </div>
            <div className="glass-card p-6 rounded-lg hover-lift">
              <div className="text-3xl font-bold text-accent-primary mb-2">90%</div>
              <div className="text-sm text-text-muted">Code Generated by AI</div>
            </div>
            <div className="glass-card p-6 rounded-lg hover-lift">
              <div className="text-3xl font-bold text-accent-primary mb-2">2.5k+</div>
              <div className="text-sm text-text-muted">Total Users Served</div>
            </div>
          </div>

          <div className="flex flex-col items-center justify-center gap-4 sm:flex-row">
            <Button
              onClick={scrollToWork}
              size="lg"
              className="group bg-accent-primary hover:bg-accent-primary/90 text-white hover-lift"
            >
              See the work
              <ArrowRight className="ml-2 h-4 w-4 transition-transform group-hover:translate-x-1" />
            </Button>

            <Button variant="outline" size="lg" className="hover-lift" asChild>
              <Link href="/contact">
                Get in touch
                <ExternalLink className="ml-2 h-4 w-4 transition-transform group-hover:translate-x-1 group-hover:-translate-y-1" />
              </Link>
            </Button>
          </div>

          {/* Tech Stack Preview */}
          <div className="pt-12">
            <p className="text-text-muted text-sm mb-4">Built with AI-first tools</p>
            <div className="flex items-center justify-center gap-6 flex-wrap">
              <Badge variant="outline" className="text-xs">Claude Sonnet</Badge>
              <Badge variant="outline" className="text-xs">Next.js 15</Badge>
              <Badge variant="outline" className="text-xs">TypeScript</Badge>
              <Badge variant="outline" className="text-xs">Tailwind CSS</Badge>
              <Badge variant="outline" className="text-xs">Vercel</Badge>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
